import stylistic from '@stylistic/eslint-plugin';
import jsdoc from 'eslint-plugin-jsdoc';
import jest from 'eslint-plugin-jest';

export default [
    {
        plugins: {
            '@stylistic': stylistic,
            jsdoc,
        },
        rules: {
            // Possible Problems
            'array-callback-return': ['warn'],
            'constructor-super': ['warn'],
            'for-direction': ['warn'],
            'getter-return': ['warn'],
            'no-async-promise-executor': ['warn'],
            'no-class-assign': ['warn'],
            'no-compare-neg-zero': ['warn'],
            'no-cond-assign': ['warn'],
            'no-const-assign': ['warn'],
            'no-constant-binary-expression': ['warn'],
            'no-constant-condition': ['warn'],
            'no-constructor-return': ['warn'],
            'no-control-regex': ['warn'],
            'no-debugger': ['warn'],
            'no-dupe-args': ['warn'],
            'no-dupe-class-members': ['warn'],
            'no-dupe-else-if': ['warn'],
            'no-dupe-keys': ['warn'],
            'no-duplicate-case': ['warn'],
            'no-duplicate-imports': ['warn'],
            'no-empty-character-class': ['warn'],
            'no-empty-pattern': ['warn'],
            'no-ex-assign': ['warn'],
            'no-func-assign': ['warn'],
            'no-import-assign': ['warn'],
            'no-inner-declarations': ['warn'],
            'no-invalid-regexp': ['warn'],
            'no-irregular-whitespace': ['warn'],
            'no-loss-of-precision': ['warn'],
            'no-misleading-character-class': ['warn'],
            'no-new-native-nonconstructor': ['warn'],
            'no-obj-calls': ['warn'],
            'no-promise-executor-return': ['warn'],
            'no-prototype-builtins': ['warn'],
            'no-self-assign': ['warn'],
            'no-self-compare': ['warn'],
            'no-setter-return': ['warn'],
            'no-sparse-arrays': ['warn'],
            'no-template-curly-in-string': ['warn'],
            'no-this-before-super': ['warn'],
            'no-unexpected-multiline': ['warn'],
            'no-unmodified-loop-condition': ['warn'],
            'no-unreachable': ['warn'],
            'no-unreachable-loop': ['warn'],
            'no-unsafe-finally': ['warn'],
            'no-unsafe-negation': ['warn'],
            'no-unsafe-optional-chaining': ['warn'],
            'no-unused-private-class-members': ['warn'],
            'no-unused-vars': ['warn', { caughtErrors: 'none' }],
            'no-use-before-define': ['warn'],
            'no-useless-assignment': ['warn'],
            'no-useless-backreference': ['warn'],
            'require-atomic-updates': ['warn'],
            'use-isnan': ['warn'],
            'valid-typeof': ['warn'],
            // Suggestions
            'accessor-pairs': ['warn'],
            'block-scoped-var': ['warn'],
            'camelcase': ['warn'],
            'consistent-this': ['warn'],
            'curly': ['warn'],
            'default-case': ['warn'],
            'default-case-last': ['warn'],
            'default-param-last': ['warn'],
            'dot-notation': ['warn'],
            'eqeqeq': ['warn'],
            'func-name-matching': ['warn'],
            'func-names': ['warn'],
            'func-style': ['warn', 'declaration'],
            'grouped-accessor-pairs': ['warn'],
            'logical-assignment-operators': ['warn'],
            'new-cap': ['warn'],
            'no-alert': ['warn'],
            'no-array-constructor': ['warn'],
            'no-caller': ['warn'],
            'no-case-declarations': ['warn'],
            'no-continue': ['warn'],
            'no-else-return': ['warn'],
            'no-empty': ['warn'],
            'no-empty-function': ['warn', { allow: ['arrowFunctions'] }],
            'no-empty-static-block': ['warn'],
            'no-eval': ['warn'],
            'no-extend-native': ['warn'],
            'no-extra-bind': ['warn'],
            'no-extra-boolean-cast': ['warn'],
            'no-extra-label': ['warn'],
            'no-global-assign': ['warn'],
            'no-implicit-coercion': ['warn'],
            'no-implicit-globals': ['warn'],
            'no-implied-eval': ['warn'],
            'no-invalid-this': ['warn'],
            'no-iterator': ['warn'],
            'no-labels': ['warn'],
            'no-lone-blocks': ['warn'],
            'no-loop-func': ['warn'],
            'no-multi-assign': ['warn'],
            'no-multi-str': ['warn'],
            'no-negated-condition': ['warn'],
            'no-nested-ternary': ['warn'],
            'no-new': ['warn'],
            'no-new-func': ['warn'],
            'no-new-wrappers': ['warn'],
            'no-nonoctal-decimal-escape': ['warn'],
            'no-object-constructor': ['warn'],
            'no-octal': ['warn'],
            'no-octal-escape': ['warn'],
            'no-proto': ['warn'],
            'no-regex-spaces': ['warn'],
            'no-return-assign': ['warn'],
            'no-script-url': ['warn'],
            'no-sequences': ['warn'],
            'no-shadow': ['warn'],
            'no-shadow-restricted-names': ['warn'],
            'no-throw-literal': ['warn'],
            'no-undef-init': ['warn'],
            'no-unneeded-ternary': ['warn'],
            'no-unused-expressions': ['warn'],
            'no-unused-labels': ['warn'],
            'no-useless-call': ['warn'],
            'no-useless-catch': ['warn'],
            'no-useless-computed-key': ['warn'],
            'no-useless-concat': ['warn'],
            'no-useless-constructor': ['warn'],
            'no-useless-escape': ['warn'],
            'no-useless-rename': ['warn'],
            'no-useless-return': ['warn'],
            'no-var': ['warn'],
            'no-void': ['warn'],
            'no-warning-comments': ['warn'],
            'no-with': ['warn'],
            'object-shorthand': ['warn'],
            'one-var': ['warn', 'never'],
            'operator-assignment': ['warn'],
            'prefer-arrow-callback': ['warn'],
            'prefer-const': ['warn'],
            'prefer-exponentiation-operator': ['warn'],
            'prefer-numeric-literals': ['warn'],
            'prefer-object-has-own': ['warn'],
            'prefer-object-spread': ['warn'],
            'prefer-promise-reject-errors': ['warn'],
            'prefer-regex-literals': ['warn'],
            'prefer-rest-params': ['warn'],
            'prefer-spread': ['warn'],
            'prefer-template': ['warn'],
            'radix': ['warn', 'as-needed'],
            'require-await': ['warn'],
            'require-unicode-regexp': ['warn'],
            'require-yield': ['warn'],
            'strict': ['warn'],
            'symbol-description': ['warn'],
            'yoda': ['warn'],
            // Layout & Formatting
            'unicode-bom': ['warn'],

            '@stylistic/arrow-parens': ['warn'],
            '@stylistic/comma-dangle': ['warn', 'always-multiline'],
            '@stylistic/comma-style': ['warn'],
            '@stylistic/dot-location': ['warn', 'property'],
            '@stylistic/eol-last': ['warn'],
            '@stylistic/linebreak-style': ['warn'],
            '@stylistic/max-statements-per-line': ['warn'],
            '@stylistic/new-parens': ['warn'],
            '@stylistic/no-confusing-arrow': ['warn'],
            '@stylistic/no-extra-parens': ['warn'],
            '@stylistic/no-extra-semi': ['warn'],
            '@stylistic/no-floating-decimal': ['warn'],
            '@stylistic/no-multiple-empty-lines': ['warn', { max: 1, maxEOF: 0 }],
            '@stylistic/operator-linebreak': ['warn', 'before'],
            '@stylistic/padded-blocks': ['warn', 'never'],
            '@stylistic/quote-props': ['warn', 'consistent-as-needed'],
            '@stylistic/quotes': ['warn', 'single'],
            '@stylistic/semi': ['warn'],
            '@stylistic/semi-style': ['warn'],
            '@stylistic/spaced-comment': ['warn'],

            'jsdoc/check-access': ['warn'],
            'jsdoc/check-alignment': ['warn'],
            'jsdoc/check-indentation': ['warn'],
            'jsdoc/check-line-alignment': ['warn'],
            'jsdoc/check-param-names': ['warn'],
            'jsdoc/check-property-names': ['warn'],
            'jsdoc/check-tag-names': ['warn'],
            'jsdoc/check-types': ['warn'],
            'jsdoc/check-values': ['warn'],
            'jsdoc/empty-tags': ['warn'],
            'jsdoc/implements-on-classes': ['warn'],
            'jsdoc/informative-docs': ['warn'],
            'jsdoc/multiline-blocks': ['warn'],
            'jsdoc/no-bad-blocks': ['warn'],
            'jsdoc/no-blank-block-descriptions': ['warn'],
            'jsdoc/no-blank-blocks': ['warn'],
            'jsdoc/no-multi-asterisks': ['warn'],
            'jsdoc/require-asterisk-prefix': ['warn'],
            'jsdoc/require-description': ['warn'],
            'jsdoc/require-description-complete-sentence': ['warn'],
            'jsdoc/require-hyphen-before-param-description': ['warn', 'never'],
            'jsdoc/require-param': ['warn'],
            'jsdoc/require-param-description': ['warn'],
            'jsdoc/require-param-name': ['warn'],
            'jsdoc/require-param-type': ['warn'],
            'jsdoc/require-property': ['warn'],
            'jsdoc/require-property-description': ['warn'],
            'jsdoc/require-property-name': ['warn'],
            'jsdoc/require-property-type': ['warn'],
            'jsdoc/require-returns': ['warn'],
            'jsdoc/require-returns-check': ['warn'],
            'jsdoc/require-returns-description': ['warn'],
            'jsdoc/require-returns-type': ['warn'],
            'jsdoc/require-throws': ['warn'],
            'jsdoc/require-yields': ['warn'],
            'jsdoc/require-yields-check': ['warn'],
            'jsdoc/tag-lines': ['warn', 'any', { startLines: 1 }],
            'jsdoc/valid-types': ['warn'],
        },
    },
    {
        files: [
            '**/__tests__/*',
        ],
        plugins: {
            jest,
        },
        rules: {
            'jest/consistent-test-it': ['warn'],
            'jest/expect-expect': ['warn'],
            'jest/no-alias-methods': ['warn'],
            'jest/no-commented-out-tests': ['warn'],
            'jest/no-conditional-in-test': ['warn'],
            'jest/no-confusing-set-timeout': ['warn'],
            'jest/no-deprecated-functions': ['warn'],
            'jest/no-disabled-tests': ['warn'],
            'jest/no-done-callback': ['warn'],
            'jest/no-duplicate-hooks': ['warn'],
            'jest/no-export': ['warn'],
            'jest/no-focused-tests': ['warn'],
            'jest/no-identical-title': ['warn'],
            'jest/no-jasmine-globals': ['warn'],
            'jest/no-mocks-import': ['warn'],
            'jest/no-standalone-expect': ['warn'],
            'jest/no-test-prefixes': ['warn'],
            'jest/no-test-return-statement': ['warn'],
            'jest/padding-around-after-all-blocks': ['warn'],
            'jest/padding-around-after-each-blocks': ['warn'],
            'jest/padding-around-before-all-blocks': ['warn'],
            'jest/padding-around-before-each-blocks': ['warn'],
            'jest/padding-around-describe-blocks': ['warn'],
            'jest/padding-around-test-blocks': ['warn'],
            'jest/prefer-called-with': ['warn'],
            'jest/prefer-comparison-matcher': ['warn'],
            'jest/prefer-each': ['warn'],
            'jest/prefer-equality-matcher': ['warn'],
            'jest/prefer-expect-resolves': ['warn'],
            'jest/prefer-hooks-in-order': ['warn'],
            'jest/prefer-hooks-on-top': ['warn'],
            'jest/prefer-jest-mocked': ['warn'],
            'jest/prefer-lowercase-title': ['warn'],
            'jest/prefer-mock-promise-shorthand': ['warn'],
            'jest/prefer-spy-on': ['warn'],
            'jest/prefer-strict-equal': ['warn'],
            'jest/prefer-to-be': ['warn'],
            'jest/prefer-to-contain': ['warn'],
            'jest/prefer-to-have-length': ['warn'],
            'jest/prefer-todo': ['warn'],
            'jest/require-hook': ['warn'],
            'jest/require-to-throw-message': ['warn'],
            'jest/valid-describe-callback': ['warn'],
            'jest/valid-expect': ['warn'],
            'jest/valid-expect-in-promise': ['warn'],
            'jest/valid-title': ['warn'],
        },
    },
];
